Branch develop - 2° commit
Adolf-Mtt/Sprint_6 pull request #1
Opened 2023-10-20 14:14 UTC by Adolf-Mtt

2023-10-22 06:19 UTC, francieletripleten requested changes

2023-10-22 06:19 UTC, francieletripleten commented on create_kit_name_kit_test.py
Como buena práctica de programación, elimine las líneas en blanco en exceso entre las importaciones y las funciones. Deje solo una línea en blanco antes de su comentario para comenzar las funciones.

2023-10-22 06:19 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +    var = sender_stand_request.get_kit_table()
Proporcione una descripción más explícita para la variable "var", ya que esta variable almacenará el resultado de la respuesta de get_kit_table.
Agregue el atributo .text (que normalmente se utiliza para acceder al contenido de la respuesta en formato de texto) después de la función get_kit_table().

2023-10-22 06:19 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +    assert str(response.json()["id"]) in var.text and response.json()["name"] in var.text.replace("\\","") # Valor esperado = True / Positivo
En la aserción, elimine el parámetro .text de la variable "var" en ambas ocasiones en que se utiliza.

2023-10-22 06:19 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +
Agregue en esta función una aserción para validar si el nombre recibido es igual al valor del parámetro "nombre" (similar a la aserción en la función "positive_assert").

2023-10-22 06:19 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +    var = sender_stand_request.get_kit_table()
Repite la misma corrección en esta prueba y asigna un nombre más descriptivo a la variable "var".

2023-10-22 06:19 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +        "name": "Abcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdabcdab
Coloca el valor del parámetro 'name' en el archivo 'data.py' y luego modifica la llamada a esta función con el nuevo parámetro creado en 'data.py'
positive_assert(data.kit_body["new_param_with_511_caracteres"]["name"])

2023-10-22 06:19 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +    kit_body = {
Coloca el valor del parámetro 'name' en el archivo 'data.py' y luego modifica la llamada a esta función con el nuevo parámetro creado en 'data.py'
negative_assert_code_400(data.kit_body["new_param_with_512_caracteres"]["name"])

2023-10-23 15:47 UTC, Adolf-Mtt commented on create_kit_name_kit_test.py
> +    var = sender_stand_request.get_kit_table()
Hacer esto: 
var = sender_stand_request.get_kit_table() 
var.text

No seria lo mismo que: 
var = sender_stand_request.get_kit_table().text 
var


Entiendo que en el llamado de la función, si no se coloca el método .text() te trae todo un objeto con toda la información . Al aplicar el método .text() en el llamado de la función solo trae el texto... Y mi pregunta especifica, ¿qué inconvenientes trae el orden de la aplicación del .text() antes o después en el código?

2023-10-23 16:55 UTC, Adolf-Mtt commented on create_kit_name_kit_test.py
> +
Acá no entiendo por qué se debe colocar un assert para comprobar el valor recibido en parámetro "name".
En esta prueba no se debería de realizar el registro, lo que debería de recibir en dado caso en un mensaje de error (ej.: "parámetros no correctos a ingresar...").
El primer assert debe ser igual a 400, al fallar (porque da código 201) el segundo assert no se ejecuta... el cual sí está en la línea 36

No entiendo esta sugerencia / corrección

2023-10-23 17:16 UTC, merged

2023-10-25 15:26 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +    var = sender_stand_request.get_kit_table()
No necesariamente es "mejor", pero la elección entre las dos opciones depende de tus necesidades en el código. La diferencia radica en el orden de acceso a los métodos y atributos.
En esta opción, primero asignas el resultado de get_kit_table() a la variable 'var' y, luego, accedes al atributo 'text' de esa variable. Esto puede ser útil si tienes la intención de utilizar el valor devuelto por get_kit_table() en múltiples partes de tu código o si deseas realizar operaciones adicionales con 'var' antes de acceder a 'text'. Esta aproximación es más explícita y legible.

2023-10-25 15:26 UTC, francieletripleten commented on create_kit_name_kit_test.py
> +
@Adolf-Mtt Esta es solo una sugerencia para hacer tu afirmación más completa. En muchos casos, la prueba negativa no incluye otros parámetros de error en la respuesta. Si este es el caso de este punto final, agrega una afirmación con el mensaje de error devuelto para el estado 400.

2023-10-26 02:09 UTC, Adolf-Mtt commented on create_kit_name_kit_test.py
> +
No puedo agregar un 'assert' para el mensaje de error 400, ya que en los requisitos del proyecto no lo indican o especifican (no cómo lo piden para las pruebas positivas - 201). Es decir, al no tener un mensaje de error el cual verificar, no lo puedo inventar porque dará error.

Como mencioné en el comentario anterior, en el código hay un 2° 'assert' de verificación, el cual revisa que en la BD no se haya realizado el ingreso (debido a que en estas pruebas, no se debería realizar un registro). 
El segundo 'assert' que me solicitas, está seguido del primer 'assert' entre las líneas 33 y 36

Dejo un print de lo que se pide en el proyecto para estas pruebas.
![Captura de pantalla 2023-10-25 223653](https://github.com/Adolf-Mtt/Sprint_6/assets/147944617/923efc05-a781-42ce-b67a-0ee79624b069)

2023-10-27 19:50 UTC, francieletripleten reviewed
¡Hola Gustavo! Me gustaría felicitarte por la entrega de tu proyecto. Aplicaste magistralmente buenas prácticas de programación, además de automatizar los escenarios positivos y negativos de los endpoints especificados en la actividad. Sigue estudiando y practicando la automatización, hasta el próximo proyecto.